// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | ""
    | "/"
    | "/background.js"
    | "/content-scripts/bookmark-dialog.js"
    | "/dialog-iframe.html"
    | "/err-icon-128.png"
    | "/err-icon-16.png"
    | "/err-icon-32.png"
    | "/err-icon-48.png"
    | "/icon-128.png"
    | "/icon-16.png"
    | "/icon-32.png"
    | "/icon-48.png"
    | "/off-icon-128.png"
    | "/off-icon-16.png"
    | "/off-icon-32.png"
    | "/off-icon-48.png"
    | "/options.html"
    | "/popup.html"
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
